const Discord = require("discord.js");
const client = new Discord.Client();
client.login(process.env.TOKEN);
client.on('message', message => {
if(message.content === ".hey"){

message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
  message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
  message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
  message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
  message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
  message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
  message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
  message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
message.channel.send("@everyone Mdr la grosse moulaaa")
message.channel.send("@everyone poursuivi par les méchants")
message.channel.send("@everyone les méchants lesmélesmélesmé les méchaaaaants")
}
});
